steps:
  # build the container image
- id: build
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/rlt-test:latest", "."]
  # push container image
- id: push
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/rlt-test:latest"]

  # Configure a kubectl workspace for this project
- name: gcr.io/cloud-builders/kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
    - KUBECONFIG=/workspace/.kube/config